/**
 * AYURAI — STABLE DEMO MODE DATASET
 * 
 * Authentic, classical Ayurvedic clinical demonstration dataset
 * Compliant with Charaka Samhita & Sushruta Samhita clinical standards.
 * 
 * IMPORTANT SAFETY & COMPLIANCE NOTICE:
 * - All patient records are purely fictional for hackathon demonstration.
 * - AI summaries are assistive drafts requiring Vaidya verification.
 * - OCR extractions are simulated demo records.
 */

export const DEMO_CONFIG = {
  isDemoMode: true,
  demoTag: 'SIH DEMO MODE',
  disclaimer: 'AI-assisted draft — practitioner review required. Final clinical decisions remain with the qualified practitioner.',
  aiDemoBanner: 'AI DEMO — SIMULATED ASSISTIVE SUMMARY',
  ocrDemoBanner: 'Demo OCR result — for practitioner verification',
};

export const DEMO_ROLES = {
  PATIENT: 'patient',
  DOCTOR: 'doctor',
  STAFF: 'staff',
  ADMIN: 'admin',
};

export const DEMO_CREDENTIALS = [
  { role: 'doctor', email: 'doctor@demo.ayurai', altEmail: 'doctor@ayurai.com', password: 'demo123', name: 'Vaidya Dr. K. Rajesh Sharma', route: '/doctor' },
  { role: 'staff', email: 'staff@demo.ayurai', altEmail: 'staff@ayurai.com', password: 'demo123', name: 'Nurse S. Meenakshi', route: '/staff' },
  { role: 'admin', email: 'admin@demo.ayurai', altEmail: 'admin@ayurai.com', password: 'demo123', name: 'Medical Superintendent (Admin)', route: '/admin' },
  { role: 'patient', email: 'patient@demo.ayurai', altEmail: 'patient@ayurai.com', password: 'demo123', name: 'Ananya S. Rao', route: '/patient' },
];

export const DEMO_DOCTORS = [
  {
    id: 'doc-1',
    name: 'Vaidya Dr. K. Rajesh Sharma',
    qualification: 'BAMS, MD (Kayachikitsa - BHU)',
    specialty: 'Kayachikitsa (Internal Medicine) & Metabolic Disorders',
    experience: '16 Years',
    roomNo: 'OPD-102',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    status: 'On Duty',
    consultationsToday: 18,
    averageTimePerPatient: '12 mins',
  },
  {
    id: 'doc-2',
    name: 'Vaidya Dr. Priya S. Nair',
    qualification: 'BAMS, MD (Panchakarma - Kerala)',
    specialty: 'Panchakarma & Chronic Rheumatology',
    experience: '12 Years',
    roomNo: 'OPD-104',
    avatar: 'https://images.unsplash.com/photo-1594824813596-78401306ef45?w=150&auto=format&fit=crop&q=80',
    status: 'On Duty',
    consultationsToday: 14,
    averageTimePerPatient: '15 mins',
  },
  {
    id: 'doc-3',
    name: 'Vaidya Dr. Anand Deshmukh',
    qualification: 'BAMS, MS (Ayurveda)',
    specialty: 'Shalya Tantra & Gut Health',
    experience: '9 Years',
    roomNo: 'OPD-106',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    status: 'In Procedure',
    consultationsToday: 11,
    averageTimePerPatient: '18 mins',
  },
  {
    id: 'doc-4',
    name: 'Vaidya Dr. Sunita Kulkarni',
    qualification: 'BAMS, MD (Prasuti Tantra)',
    specialty: 'Prasuti & Stri Roga',
    experience: '14 Years',
    roomNo: 'OPD-108',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    status: 'Available',
    consultationsToday: 9,
    averageTimePerPatient: '14 mins',
  },
];

export const DEMO_STAFF = [
  {
    id: 'st-1',
    name: 'Nurse S. Meenakshi',
    role: 'Chief Triage Nurse',
    desk: 'Frontdesk Counter 1',
    shift: 'Morning (08:00 - 16:00)',
    status: 'Active',
    verifiedToday: 24,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-2',
    name: 'R. K. Venkatesh',
    role: 'Registration Receptionist',
    desk: 'Frontdesk Counter 2',
    shift: 'Morning (08:00 - 16:00)',
    status: 'Active',
    verifiedToday: 19,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-3',
    name: 'A. Lakshmi',
    role: 'Herbal Pharmacy Lead',
    desk: 'Dispensary Counter 4',
    shift: 'Full Day (09:00 - 18:00)',
    status: 'Active',
    verifiedToday: 32,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-4',
    name: 'M. Harish Kumar',
    role: 'Kiosk & Queue Assistant',
    desk: 'Waiting Lounge Area',
    shift: 'Morning (08:00 - 16:00)',
    status: 'Active',
    verifiedToday: 15,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
];

export const DEMO_PATIENTS = [
  {
    id: 'pat-101',
    uhid: 'AYUR-2026-0891',
    name: 'Ananya S. Rao',
    dob: '1988-05-14',
    age: 38,
    gender: 'Female',
    phone: '+91 98450 12345',
    email: 'ananya.rao@example.com',
    address: 'No. 42, 4th Main Road, Indiranagar, Bengaluru - 560038',
    emergencyContact: '+91 98450 99887 (Srinivasa Rao - Spouse)',
    occupation: 'Senior Software Architect',
    preferredLanguage: 'ta',
    tokenNumber: 'A-024',
    tokenStatus: 'waiting',
    queuePosition: 2,
    estimatedWaitMins: 15,
    priority: 'Potential Red Flag — Review Required',
    registrationTime: '09:15 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Chronic hyperacidity (Amlapitta), retrosternal burning after spicy food, and morning joint stiffness.',
    duration: '6 months',
    vitals: {
      pulse: 78,
      bp: '124/82',
      weight: 62,
      height: 164,
      bmi: '23.1',
      temperature: '98.4 F',
    },
    prakriti: {
      primary: 'Pitta-Vata',
      vata: 35,
      pitta: 50,
      kapha: 15,
      vikriti: 'Pitta Vriddhi with Vata Anubandha (Urdhwaga Amlapitta)',
    },
    agniStatus: 'Tikshna Agni (Intense burning hunger)',
    koshthaStatus: 'Mridu Koshtha (Soft/loose stools, sensitive to milk)',
    caseIntake: {
      primaryCategory: 'gastrointestinal',
      chiefComplaint: 'வயிற்றில் கடுமையான நெஞ்செரிச்சல், புளித்த ஏப்பம் மற்றும் காலையில் மூட்டு பிடிப்பு (Chronic retrosternal burning and hyperacidity with morning stiffness)',
      duration: '6 months',
      severity: 6,
      giRelation: 'empty_stomach',
      appetite: 'Tikshna Agni (Intense burning hunger)',
      bowel: 'Mridu Koshtha (2-3 loose motions with burning sensation)',
      sleep: 'Disturbed / Early morning waking at 4 AM (Vata)',
      stress: 'Moderate work-related stress, perfectionist tendency',
      dietHabits: 'Frequent tea/coffee, spicy fermented foods, irregular meal timings',
      physicalActivity: 'Sedentary desk job with 20 mins light evening walking',
      pastTreatments: 'Antacids (Pantoprazole 40mg) for 3 months with partial relief.',
    },
    medicalHistory: {
      pastIllnesses: 'Occasional migraine episodes (2021-2023), Mild GERD',
      surgeries: 'None',
      allergies: 'Penicillin (Skin rash), Dust / Pollen allergy',
      currentMedicines: 'Pantoprazole 40mg OD (Occasional)',
      familyHistory: 'Father: Hypertension; Mother: Osteoarthritis (Janu Sandhigata Vata)',
      habits: 'Non-smoker, Tea (3 cups daily), No alcohol',
    },
    ashtavidhaAssessment: {
      nadi: 'Manduka Gati (Frog jump, Pitta dominant, 78 bpm)',
      jihwa: 'Raktavarna with mild yellow coating at center (Samata)',
      mutra: 'Peeta varna, mild burning micturition',
      mala: 'Peetabha, Mridu, Sasneha',
      shabda: 'Spashta (Clear & resonant)',
      sparsha: 'Ushna (Warm to touch)',
      drik: 'Rakta-Pitaabh (Mild conjunctival hyperemia)',
      akriti: 'Madhyama (Medium built)',
    },
    dashavidhaAssessment: {
      prakriti: 'Pitta-Vata',
      vikriti: 'Pitta Vriddhi',
      sara: 'Rasa-Rakta Madhyama',
      samhanana: 'Madhyama Symmetry',
      pramana: 'Normal BMI (23.1)',
      satmya: 'Ghritha Satmya',
      satva: 'Madhyama Satva',
      aharaShakti: 'Tikshna Intake',
      vyayamaShakti: 'Madhyama Stamina',
      vaya: 'Madhyama (38y)',
    },
    redFlags: [
      {
        id: 'rf-1',
        level: 'practitioner_review',
        title: 'Chronic Retrosternal Burning & Prolonged Antacid Dependency',
        desc: '6-month history of burning with sour regurgitation; warrants Vaidya review for mucosal irritation (Urdhwaga Amlapitta) vs ulceration.',
        action: 'Prioritize in current OPD session for pulse and tongue verification.',
      },
      {
        id: 'rf-2',
        level: 'informational',
        title: 'Reported Penicillin Drug Allergy',
        desc: 'Documented allopathic antibiotic allergy. Safe for Classical Ayurvedic herbs.',
        action: 'Noted in Patient Safety Log.',
      },
    ],
    documents: [
      { id: 'doc-d1', name: 'Upper_GI_Endoscopy_Report.pdf', type: 'imaging', date: '2026-07-15', size: '2.4 MB', status: 'Indexed & Processed', extractedData: 'Demo OCR result: Mild diffuse antral erythema; no active ulceration.' },
      { id: 'doc-d2', name: 'Lipid_and_LFT_Profile.pdf', type: 'labReport', date: '2026-08-10', size: '1.1 MB', status: 'Indexed & Processed', extractedData: 'Demo OCR result: SGOT 28 U/L, SGPT 32 U/L, Hb 13.8 g/dL (Normal range).' },
    ],
    summaryStatus: 'needs_review',
    consultationNotes: 'Intake symptoms consistent with Urdhwaga Amlapitta with Pitta-Vata dushti. Initiating Pitta Shamana with Deepana-Pachana.',
    prescriptions: [
      {
        id: 'rx-101',
        date: '2026-09-07',
        status: 'Active',
        diagnosis: 'Urdhwaga Amlapitta (Hyperacidity Syndrome)',
        issuedBy: 'Vaidya Dr. K. Rajesh Sharma',
        items: [
          { medicine_name: 'Avipattikar Churna', form: 'Churna', dosage: '3 to 5 grams', frequency: 'Twice daily (BD)', timing: 'Abhakta (30 mins before food)', anupana: 'Lukewarm water or Honey', duration: '15 Days', instructions: 'Take before breakfast and dinner' },
          { medicine_name: 'Praval Pishti', form: 'Pishti / Bhasma', dosage: '250 mg', frequency: 'Twice daily (BD)', timing: 'Pragbhakta (With first morsel of food)', anupana: 'Gulkand or tender coconut water', duration: '15 Days', instructions: 'Pacifies active burning sensation' },
          { medicine_name: 'Maharasnadi Kashayam', form: 'Kashayam', dosage: '15 ml + 45 ml warm water', frequency: 'Once daily (OD)', timing: 'Early morning empty stomach', anupana: 'Lukewarm water', duration: '15 Days', instructions: 'For morning joint stiffness' },
        ],
        pathya_rules: 'Old Basmati rice, Moong dal soup (Mudga Yusha), Cow Ghee in moderation, Pomegranate, Tender coconut water, boiled cooled water.',
        apathya_rules: 'Excessive green chilies, sour curds, deep fried snacks, vinegar, late dinners after 10:30 PM, daytime sleeping.',
        follow_up_date: '2026-09-21',
      },
    ],
    followUp: {
      nextDate: '2026-09-21',
      timeSlot: '10:30 AM',
      interval: '14 Days',
      status: 'Scheduled',
      reason: 'Evaluate Pitta pacification and resolution of retrosternal burning.',
    },
  },
  {
    id: 'pat-102',
    uhid: 'AYUR-2026-0892',
    name: 'Rajeshwari Krishnan',
    dob: '1974-11-20',
    age: 52,
    gender: 'Female',
    phone: '+91 94441 67890',
    email: 'rajeshwari.k@example.com',
    address: 'Plot 12, Gandhi Nagar, Chennai - 600020',
    emergencyContact: '+91 94441 12344 (Krishnan - Husband)',
    occupation: 'School Teacher',
    preferredLanguage: 'ta',
    tokenNumber: 'A-025',
    tokenStatus: 'waiting',
    queuePosition: 3,
    estimatedWaitMins: 25,
    priority: 'Normal',
    registrationTime: '09:20 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Bilateral knee pain (Janu Sandhigata Vata), crepitus on walking, and calf cramps during night.',
    duration: '1.5 years',
    vitals: {
      pulse: 72,
      bp: '136/88',
      weight: 71,
      height: 158,
      bmi: '28.4',
      temperature: '98.2 F',
    },
    prakriti: {
      primary: 'Vata-Kapha',
      vata: 55,
      pitta: 20,
      kapha: 25,
      vikriti: 'Vata Prakopa in Sandhi & Asthi Dhatu',
    },
    caseIntake: {
      primaryCategory: 'musculoskeletal',
      chiefComplaint: 'இரு முழங்கால்களிலும் தாங்க முடியாத வலி மற்றும் காலை நேர பிடிப்பு (Severe bilateral knee pain with morning stiffness)',
      duration: '1.5 years',
      severity: 7,
      jointStiffness: 'morning_stiffness_1hr',
      appetite: 'Vishama Agni (Variable)',
      bowel: 'Krura Koshtha (Hard dry stools, tendency to constipation)',
      sleep: 'Light and interrupted by knee ache',
      stress: 'Anxious regarding mobility loss',
      dietHabits: 'Vegetarian, low ghee intake, cold beverages',
      physicalActivity: 'Limited due to joint discomfort',
      pastTreatments: 'Painkillers (Aceclofenac) on SOS basis.',
    },
    medicalHistory: {
      pastIllnesses: 'Hypothyroidism (diagnosed 2018)',
      surgeries: 'None',
      allergies: 'Sulpha drugs',
      currentMedicines: 'Thyronorm 50 mcg OD',
      familyHistory: 'Mother had severe arthritis',
      habits: 'Vegetarian, tea lover',
    },
    documents: [
      { id: 'doc-d3', name: 'Bilateral_Knee_XRay.pdf', type: 'imaging', date: '2026-06-20', size: '4.8 MB', status: 'Indexed & Processed', extractedData: 'Demo OCR result: Bilateral knee medial joint space narrowing; osteophyte formation.' },
    ],
  },
  {
    id: 'pat-103',
    uhid: 'AYUR-2026-0893',
    name: 'Arvind M. Kumar',
    dob: '1982-08-05',
    age: 44,
    gender: 'Male',
    phone: '+91 98800 45678',
    email: 'arvind.kumar@example.com',
    address: 'Flat 302, Green Glen Layout, Bellandur, Bengaluru',
    emergencyContact: '+91 98800 11223',
    occupation: 'Financial Analyst',
    preferredLanguage: 'kn',
    tokenNumber: 'A-021',
    tokenStatus: 'in_consultation',
    queuePosition: 0,
    estimatedWaitMins: 0,
    priority: 'Normal',
    registrationTime: '09:05 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Post-prandial heaviness (Ajeerna), lethargy, sluggish metabolism, and weight gain around abdomen.',
    duration: '4 months',
    vitals: {
      pulse: 68,
      bp: '128/84',
      weight: 84,
      height: 172,
      bmi: '28.4',
      temperature: '98.6 F',
    },
    prakriti: {
      primary: 'Kapha-Pitta',
      vata: 20,
      pitta: 35,
      kapha: 45,
      vikriti: 'Kapha-Meda Dhatvagni Mandya with Ama',
    },
    caseIntake: {
      primaryCategory: 'gastrointestinal',
      chiefComplaint: 'ಊಟದ ನಂತರ ವಿಪರೀತ ಹೊಟ್ಟೆ ಭಾರ, ಆಲಸ್ಯ ಮತ್ತು ತೂಕ ಹೆಚ್ಚಳ (Post-prandial heaviness and sluggish digestion)',
      duration: '4 months',
      severity: 5,
      appetite: 'Manda Agni (Slow, lacks hunger for 5-6 hrs)',
      bowel: 'Madhyama Koshtha with sticky unformed stools (Sama)',
      sleep: 'Heavy deep sleep, daytime sleepiness (Divasvapna)',
      stress: 'Calm, lethargic',
      dietHabits: 'High carbohydrate, sweets, dairy and fried snacks in evening',
      physicalActivity: 'Minimal exercise',
    },
    medicalHistory: {
      pastIllnesses: 'Prediabetes / Borderline HbA1c 6.1%',
      surgeries: 'None',
      allergies: 'None reported',
      currentMedicines: 'None',
      familyHistory: 'Type 2 Diabetes Mellitus (Both parents)',
      habits: 'Sedentary work, late night dinner',
    },
    documents: [
      { id: 'doc-d4', name: 'Fasting_Blood_Sugar_Report.pdf', type: 'labReport', date: '2026-08-28', size: '890 KB', status: 'Indexed & Processed', extractedData: 'Demo OCR result: Fasting Blood Sugar 108 mg/dL, HbA1c 6.1%.' },
    ],
  },
  {
    id: 'pat-104',
    uhid: 'AYUR-2026-0894',
    name: 'Vikas Sharma',
    dob: '1978-03-12',
    age: 48,
    gender: 'Male',
    phone: '+91 98110 55667',
    email: 'vikas.sharma@example.com',
    address: 'B-12, Sector 14, Noida, UP',
    emergencyContact: '+91 98110 99881 (Sunita - Wife)',
    occupation: 'Civil Engineer',
    preferredLanguage: 'hi',
    tokenNumber: 'A-026',
    tokenStatus: 'case_taking',
    queuePosition: 4,
    estimatedWaitMins: 35,
    priority: 'Potential Red Flag — Review Required',
    registrationTime: '09:30 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Chronic dry cough (Vataja Kasa), throat irritation in morning, and mild breathlessness after exertion.',
    duration: '3 months',
    vitals: {
      pulse: 76,
      bp: '130/84',
      weight: 74,
      height: 170,
      bmi: '25.6',
      temperature: '98.4 F',
    },
    prakriti: {
      primary: 'Vata-Pitta',
      vata: 50,
      pitta: 35,
      kapha: 15,
      vikriti: 'Pranavaha Srotas Dushti with Vata Prakopa',
    },
    caseIntake: {
      primaryCategory: 'respiratory',
      chiefComplaint: 'लगातार सूखी खांसी, गले में सूखापन एवं सुबह उठने पर सांस लेने में हल्की रुकावट (Chronic dry cough with throat tickle)',
      duration: '3 months',
      severity: 6,
      appetite: 'Sama Agni',
      bowel: 'Krura Koshtha (Dry stools)',
      sleep: 'Disturbed due to nocturnal coughing bouts',
      stress: 'Moderate work stress',
      dietHabits: 'Cold water intake, dusty outdoor work environment',
    },
    medicalHistory: {
      pastIllnesses: 'Seasonal allergic rhinitis',
      surgeries: 'None',
      allergies: 'Dust, pollen, cold drinks',
      currentMedicines: 'None',
      familyHistory: 'Father: Bronchial asthma',
      habits: 'Non-smoker',
    },
    redFlags: [
      {
        id: 'rf-5',
        level: 'practitioner_review',
        title: '3-Month Chronic Unresolved Cough',
        desc: 'Persistent Vataja Kasa unresponsive to conventional syrups. Requires examination for Pranavaha Srotas obstruction.',
        action: 'Prescribe Kantakari Avaleha and Talisadi Churna.',
      },
    ],
    documents: [
      { id: 'doc-d5', name: 'Chest_XRay_PA_View.pdf', type: 'imaging', date: '2026-07-20', size: '3.1 MB', status: 'Indexed & Processed', extractedData: 'Demo OCR result: Normal lung fields; no active consolidation or pleural effusion.' },
    ],
  },
  {
    id: 'pat-105',
    uhid: 'AYUR-2026-0895',
    name: 'David Miller',
    dob: '1991-07-24',
    age: 35,
    gender: 'Male',
    phone: '+91 99000 88990',
    email: 'david.miller@example.com',
    address: 'Whitefield Palm Meadows, Bengaluru',
    emergencyContact: '+91 99000 77881',
    occupation: 'VP of Engineering',
    preferredLanguage: 'en',
    tokenNumber: 'A-022',
    tokenStatus: 'waiting',
    queuePosition: 1,
    estimatedWaitMins: 5,
    priority: 'Priority Validated',
    registrationTime: '09:10 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Severe chronic insomnia (Anidra), racing mind at night, restlessness, and daytime brain fog.',
    duration: '5 months',
    vitals: {
      pulse: 82,
      bp: '126/80',
      weight: 68,
      height: 178,
      bmi: '21.5',
      temperature: '98.6 F',
    },
    prakriti: {
      primary: 'Vata-Pitta',
      vata: 60,
      pitta: 30,
      kapha: 10,
      vikriti: 'Manovaha Srotas Vata Prakopa with Rajasic aggravation',
    },
    caseIntake: {
      primaryCategory: 'neurological',
      chiefComplaint: 'Severe sleep-onset insomnia, racing thoughts past midnight, high occupational stress.',
      duration: '5 months',
      severity: 7,
      appetite: 'Vishama Agni',
      bowel: 'Krura Koshtha',
      sleep: 'Less than 4 hours broken sleep',
      stress: 'Severe high-stress executive workload',
      dietHabits: 'High caffeine (4 cups espresso daily), late night screen time',
    },
    medicalHistory: {
      pastIllnesses: 'Workplace burnout (2024)',
      surgeries: 'None',
      allergies: 'None',
      currentMedicines: 'Melatonin 5mg (SOS)',
      familyHistory: 'Non-contributory',
      habits: 'Coffee lover, non-smoker',
    },
    documents: [
      { id: 'doc-d6', name: 'Sleep_Study_Summary.pdf', type: 'labReport', date: '2026-06-15', size: '1.4 MB', status: 'Indexed & Processed', extractedData: 'Demo OCR result: Reduced sleep efficiency (62%); prolonged sleep latency.' },
    ],
  },
  {
    id: 'pat-106',
    uhid: 'AYUR-2026-0896',
    name: 'Meera Patel',
    dob: '1997-04-18',
    age: 29,
    gender: 'Female',
    phone: '+91 97230 44556',
    email: 'meera.patel@example.com',
    address: 'Navrangpura, Ahmedabad, Gujarat',
    emergencyContact: '+91 97230 11223',
    occupation: 'Architect',
    preferredLanguage: 'hi',
    tokenNumber: 'A-027',
    tokenStatus: 'assessment',
    queuePosition: 5,
    estimatedWaitMins: 45,
    priority: 'Normal',
    registrationTime: '09:35 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Skin dryness and eczema flare-up (Vicharchika) with seasonal weather changes.',
    duration: '2 months',
    vitals: { pulse: 74, bp: '118/78', weight: 58, height: 162, bmi: '22.1', temperature: '98.4 F' },
    prakriti: { primary: 'Pitta-Kapha', vata: 25, pitta: 45, kapha: 30, vikriti: 'Rakta Dhatu Dushti' },
    documents: [],
  },
  {
    id: 'pat-107',
    uhid: 'AYUR-2026-0897',
    name: 'Suresh Menon',
    dob: '1965-02-10',
    age: 61,
    gender: 'Male',
    phone: '+91 94470 33445',
    email: 'suresh.menon@example.com',
    address: 'Kaloor, Kochi, Kerala',
    emergencyContact: '+91 94470 99881',
    occupation: 'Retired Bank Manager',
    preferredLanguage: 'ml',
    tokenNumber: 'A-019',
    tokenStatus: 'completed',
    queuePosition: 0,
    estimatedWaitMins: 0,
    priority: 'Normal',
    registrationTime: '08:45 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Lumbar spondylosis review post-Katy Basti therapy.',
    duration: '1 year',
    vitals: { pulse: 70, bp: '132/84', weight: 76, height: 168, bmi: '26.9', temperature: '98.2 F' },
    prakriti: { primary: 'Vata-Pitta', vata: 50, pitta: 35, kapha: 15, vikriti: 'Vata Shamana complete' },
    documents: [],
  },
  {
    id: 'pat-108',
    uhid: 'AYUR-2026-0898',
    name: 'Lakshmi Narayanan',
    dob: '1971-09-25',
    age: 55,
    gender: 'Female',
    phone: '+91 98410 77889',
    email: 'lakshmi.n@example.com',
    address: 'Mylapore, Chennai, Tamil Nadu',
    emergencyContact: '+91 98410 22334',
    occupation: 'Homemaker',
    preferredLanguage: 'ta',
    tokenNumber: 'A-018',
    tokenStatus: 'follow_up',
    queuePosition: 0,
    estimatedWaitMins: 0,
    priority: 'Normal',
    registrationTime: '08:30 AM',
    assignedDoctorId: 'doc-1',
    assignedDoctorName: 'Vaidya Dr. K. Rajesh Sharma',
    assignedDepartment: 'Kayachikitsa (Internal Medicine)',
    assignedRoom: 'OPD-102',
    chiefComplaint: 'Routine 30-day follow-up for Amlapitta treatment progress.',
    duration: '30 days',
    vitals: { pulse: 72, bp: '122/80', weight: 64, height: 155, bmi: '26.6', temperature: '98.4 F' },
    prakriti: { primary: 'Pitta-Vata', vata: 40, pitta: 45, kapha: 15, vikriti: 'Pitta Shamana in progress' },
    documents: [],
  },
];

export const DEMO_FORMULATIONS = [
  {
    id: 'form-1',
    name: 'Avipattikar Churna',
    type: 'Churna (Herbal Powder)',
    classicalReference: 'Bhaishajya Ratnavali',
    doshaTarget: 'Pitta Dosha (Pitta Rechana & Agni Deepana)',
    indications: 'Amlapitta (Hyperacidity), Vidagdha Jeerna, Heartburn, Constipation with Pitta',
    standardDosage: '3 to 5 grams twice daily',
    anupana: 'Lukewarm water or Honey / Coconut water',
    timing: 'Samana Kala (Between meals or 30 mins before food)',
  },
  {
    id: 'form-2',
    name: 'Praval Pishti',
    type: 'Pishti / Bhasma (Processed Coral Calx)',
    classicalReference: 'Ayurveda Sara Sangraha',
    doshaTarget: 'Pitta Shamaka & Dahashamaka',
    indications: 'Amlapitta, Burning sensation, Hyperacidity, Raktapitta',
    standardDosage: '250 mg twice daily',
    anupana: 'Gulkand, Honey, or Butter',
    timing: 'Pragbhakta (With first morsel of meal)',
  },
  {
    id: 'form-3',
    name: 'Maharasnadi Kashayam',
    type: 'Kashayam (Decoction)',
    classicalReference: 'Sahasrayogam / Sharangadhara Samhita',
    doshaTarget: 'Vata Dosha (Vata-Kapha Harana)',
    indications: 'Sandhigata Vata (Osteoarthritis), Amavata (Rheumatoid arthritis), Gridhrasi (Sciatica)',
    standardDosage: '15 ml Kashayam diluted with 45 ml lukewarm water twice daily',
    anupana: 'Lukewarm water / Ginger juice / Shunthi Churna',
    timing: 'Abhakta (Before meals on empty stomach)',
  },
  {
    id: 'form-4',
    name: 'Yogaraj Guggulu',
    type: 'Vati / Guggulu (Purified Resin Tablet)',
    classicalReference: 'Bhaishajya Ratnavali / Yogaratnakara',
    doshaTarget: 'Vata-Kapha Shamaka',
    indications: 'Joint stiffness, Vataja Shirashoola, Asthi-Majja Dhatu Gata Vata',
    standardDosage: '2 tablets (500mg each) twice daily',
    anupana: 'Warm water / Maharasnadi Kashayam / Warm milk',
    timing: 'Adhobhakta (After meals)',
  },
  {
    id: 'form-5',
    name: 'Triphala Churna',
    type: 'Churna (Tri-herbal Blend)',
    classicalReference: 'Charaka Samhita Chikitsa Sthana',
    doshaTarget: 'Tridoshahara (Balances Vata, Pitta & Kapha)',
    indications: 'Koshtha Shuddhi (Gentle bowel regulator), Rasayana, Chakshushya',
    standardDosage: '3 to 6 grams at bedtime',
    anupana: 'Warm water or Honey with Ghee in unequal proportions',
    timing: 'Nishi (At bedtime)',
  },
  {
    id: 'form-6',
    name: 'Ashwagandharishta',
    type: 'Arishta (Fermented Formulation)',
    classicalReference: 'Bhaishajya Ratnavali Murcha Roga',
    doshaTarget: 'Vata-Kaphahara, Balya & Medhya',
    indications: 'Manasika Shrama (Mental exhaustion), insomnia, nervous debility, Rasayana',
    standardDosage: '20 ml with equal quantity of water twice daily',
    anupana: 'Equal quantity of water',
    timing: 'Adhobhakta (Immediately after meals)',
  },
  {
    id: 'form-7',
    name: 'Kamadudha Rasa (Mukta Yukta)',
    type: 'Rasa / Kharaliya Rasayana',
    classicalReference: 'Rasendra Sara Sangraha',
    doshaTarget: 'Pitta Shamaka & Daha Shamaka',
    indications: 'Gastric ulcer, hyperacidity, headache due to Pitta, vertigo',
    standardDosage: '250 mg twice daily',
    anupana: 'Cow Milk / Gulkand / Butter',
    timing: 'Samana Kala (Between meals)',
  },
  {
    id: 'form-8',
    name: 'Sitopaladi Churna',
    type: 'Churna (Respiratory Blend)',
    classicalReference: 'Sharangadhara Samhita',
    doshaTarget: 'Vata-Pitta Shamaka',
    indications: 'Kasa (Cough), Shwasa (Asthma/Bronchitis), burning sensation in hands/feet',
    standardDosage: '3 grams twice daily',
    anupana: 'Honey and Ghee in unequal ratio',
    timing: 'Muhurmuhu (Frequent small doses)',
  },
];

export const DEMO_PATHYA_APATHYA = {
  pitta: {
    pathya: [
      'Cow’s Ghee (Ghrita) in moderate quantity with warm meals',
      'Old harvested Basmati rice, Mudga (Mung dal soup)',
      'Sweet cooling fruits: Pomegranate (Dadima), Sweet Grapes (Draksha), Amla',
      'Vegetables: Bitter gourd, Bottle gourd, Ash gourd (Kushmanda)',
      'Drink cooled boiled water, coconut water, coriander/fennel infusion',
      'Mindful relaxed eating without hurry or frustration',
    ],
    apathya: [
      'Excessively sour (Amla), salty (Lavana), and pungent (Katu) spices',
      'Deep-fried foods, papad, fermented batter, hot pickles',
      'Excess tea, coffee, carbonated drinks, alcohol',
      'Skipping breakfast or prolonged daytime fasting',
      'Midday sun exposure and heated arguments',
    ],
  },
  vata: {
    pathya: [
      'Warm, freshly cooked, soupy, and unctuous (Snigdha) foods',
      'Warm milk with a pinch of nutmeg and cardamom at bedtime',
      'Sesame oil (Tila taila) whole-body self massage (Abhyanga)',
      'Sweet, sour, and mildly salted dishes',
      'Consistent daily sleep and waking routine (Dinacharya)',
    ],
    apathya: [
      'Raw salads, dry snacks, cold drinks, iced water',
      'Staying awake past midnight (Ratri Jagarana)',
      'Excessive multi-tasking and skipping meals',
      'Cold, dry, and windy environmental exposure',
    ],
  },
  kapha: {
    pathya: [
      'Warm, light, dry, and mildly spiced foods (Pungent, Bitter, Astringent)',
      'Honey (Madhu) in lukewarm water on empty stomach',
      'Barley (Yava), Horse gram (Kulatthi), Millets',
      'Active daily exercise (Vyayama) and brisk walking',
    ],
    apathya: [
      'Daytime sleeping (Divasvapna)',
      'Heavy dairy: Cheese, thick buffalo milk, ice-cream',
      'Cold drinks, heavy oily sweets, bakery items',
      'Sedentary lifestyle with prolonged sitting',
    ],
  },
};

export const DEMO_NOTIFICATIONS = [
  {
    id: 1,
    title: 'Token A-024 Called',
    desc: 'Vaidya Dr. K. Rajesh Sharma called token A-024 to OPD Suite 102.',
    time: '2 mins ago',
    type: 'token',
    isRead: false,
  },
  {
    id: 2,
    title: 'AI Draft Summary Ready',
    desc: 'Preliminary 14-section intake synthesis compiled for Ananya S. Rao.',
    time: '10 mins ago',
    type: 'ai',
    isRead: false,
  },
  {
    id: 3,
    title: 'Staff Triage Alert',
    desc: 'Potential red flag validated for token A-022 by Nurse S. Meenakshi.',
    time: '25 mins ago',
    type: 'triage',
    isRead: false,
  },
  {
    id: 4,
    title: 'Medicine Intake Reminder',
    desc: 'Reminder: Take Avipattikar Churna (3g) with warm water 30 mins before lunch.',
    time: '1 hour ago',
    type: 'reminder',
    isRead: true,
  },
];

export const DEMO_ANALYTICS = {
  todayFootfall: 24,
  activeInQueue: 8,
  completedConsultations: 16,
  avgConsultationMinutes: 13.4,
  avgWaitMinutes: 17.2,
  patientSatisfaction: '96.2%',
  doshaDistribution: [
    { name: 'Pitta Imbalance', value: 45, color: '#E11D48' },
    { name: 'Vata Imbalance', value: 35, color: '#6366F1' },
    { name: 'Kapha Imbalance', value: 20, color: '#16A34A' },
  ],
  topConditions: [
    { condition: 'Amlapitta & Agnimandya (Gut & Acidity)', count: 48, pct: '32%' },
    { condition: 'Sandhigata Vata & Amavata (Joints/Arthritis)', count: 37, pct: '25%' },
    { condition: 'Prameha & Medoroga (Metabolic & Diabetes)', count: 24, pct: '16%' },
    { condition: 'Kasa & Shwasa (Respiratory/Allergy)', count: 18, pct: '12%' },
    { condition: 'Tvak Roga (Skin / Eczema / Psoriasis)', count: 12, pct: '8%' },
    { condition: 'Manasika Shrama (Stress & Insomnia)', count: 9, pct: '7%' },
  ],
  hourlyFlow: [
    { hour: '08:00 AM', patients: 3, avgWait: 8 },
    { hour: '09:00 AM', patients: 7, avgWait: 14 },
    { hour: '10:00 AM', patients: 9, avgWait: 22 },
    { hour: '11:00 AM', patients: 8, avgWait: 18 },
    { hour: '12:00 PM', patients: 6, avgWait: 15 },
    { hour: '01:00 PM', patients: 2, avgWait: 10 },
    { hour: '02:00 PM', patients: 5, avgWait: 12 },
    { hour: '03:00 PM', patients: 6, avgWait: 16 },
  ],
};
